### ISSUE TITLE
Merkittäviä virheitä LAM-pisteiden sijainneissa

### ISSUE THREAD

**Issue by pailakka** [finnishtransportagency/metadata#3]
LAM-pisteiden sijainneissa on ainakin xls ja csv versioissa merkittäviä virheitä ja pisteet osuvat sivuun tieverkosta. Esimerkiksi "Tie 170 Kulosaari" ja "Tie 120 Odilampi", käytännössä kaikki pisteet vähintään hiukan sivussa.

**Comment by ghost** [comment]
Hei, jotain vastaavia ongelmia ollaan itsekin huomattu ja laitettu tietoa eteenpäin. Näihin tulee mahdollisesti korjausta, kun koordinaatti data haetaan jatkossa dynaamisesti, eikä näistä staattisista tiedostoista. ks.  https://groups.google.com/forum/#!category-topic/roaddigitrafficfi/kehitysehdotukset/-uKiBf2R0FM

Jatkossa mieluummin kommentit/korjausehdotukset tuonne samaiseen Google-ryhmään.

yt. Jouni

**Comment by jouniso** [comment]
Joidenkin pisteiden koordinaatteja on korjattu. Tiedon tarkkuus on 1-100 m, joten heittoja löytyy varmasti jatkossakin.
